/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SafetyContact = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'team' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const WeatherData = IDL.Record({
  'temperature' : IDL.Float64,
  'wbgt' : IDL.Float64,
  'heatCode' : IDL.Variant({
    'red' : IDL.Null,
    'orange' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  }),
  'lightningAlert' : IDL.Bool,
  'humidity' : IDL.Float64,
  'timestamp' : Time,
});
export const FieldStatus = IDL.Variant({
  'clear' : IDL.Null,
  'pre_check_pending' : IDL.Null,
  'incident_reported' : IDL.Null,
  'game_active' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const IncidentReport = IDL.Record({
  'id' : IDL.Text,
  'resolved' : IDL.Bool,
  'description' : IDL.Text,
  'reporterId' : IDL.Principal,
  'timestamp' : Time,
  'severity' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'photoBlobId' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
  'incidentType' : IDL.Variant({
    'near_miss' : IDL.Null,
    'injury' : IDL.Null,
    'hazard' : IDL.Null,
  }),
});
export const GameState = IDL.Record({
  'startTime' : IDL.Opt(Time),
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'endTime' : IDL.Opt(Time),
  'winner' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'currentInning' : IDL.Nat,
  'finalScore' : IDL.Opt(IDL.Nat),
  'fieldId' : IDL.Text,
});
export const SafetyChecklist = IDL.Record({
  'gopherHolesChecked' : IDL.Bool,
  'weatherAssessed' : IDL.Bool,
  'dugoutClear' : IDL.Bool,
  'completed' : IDL.Bool,
  'gameId' : IDL.Text,
  'fenceCappingIntact' : IDL.Bool,
  'aedLocated' : IDL.Bool,
  'basesSecured' : IDL.Bool,
  'coachId' : IDL.Principal,
  'timestamp' : Time,
  'firstAidKitPresent' : IDL.Bool,
  'pitchingMoundSafe' : IDL.Bool,
  'fieldId' : IDL.Text,
});
export const PitchCount = IDL.Record({
  'teamName' : IDL.Text,
  'pitchCount' : IDL.Nat,
  'gameId' : IDL.Text,
  'timestamp' : Time,
  'playerName' : IDL.Text,
});
export const CredentialStatus = IDL.Record({
  'badgeStatus' : IDL.Variant({ 'red' : IDL.Null, 'green' : IDL.Null }),
  'lastUpdated' : Time,
  'diamondLeaderComplete' : IDL.Bool,
  'backgroundCheckExpiry' : Time,
});
export const ActivityFeedEntry = IDL.Record({
  'agent' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSafetyContact' : IDL.Func([IDL.Text, SafetyContact], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAndUpdateLightningAlert' : IDL.Func([WeatherData], [], []),
  'createField' : IDL.Func([IDL.Text, FieldStatus], [], []),
  'createIncidentReport' : IDL.Func([IncidentReport], [], []),
  'endGame' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'fetchWeatherData' : IDL.Func([], [WeatherData], []),
  'getActivityFeed' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Time, IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getAllActiveGames' : IDL.Func([], [IDL.Vec(GameState)], ['query']),
  'getAllActiveIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getAllCompletedChecklistsForField' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SafetyChecklist)],
      ['query'],
    ),
  'getAllFields' : IDL.Func([], [IDL.Vec(FieldStatus)], ['query']),
  'getAllPitchCountsForPlayer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PitchCount)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChecklist' : IDL.Func([IDL.Text], [IDL.Opt(SafetyChecklist)], ['query']),
  'getCredentialStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CredentialStatus)],
      ['query'],
    ),
  'getField' : IDL.Func([IDL.Text], [IDL.Opt(FieldStatus)], ['query']),
  'getGameState' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
  'getIncidentReport' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IncidentReport)],
      ['query'],
    ),
  'getPitchCount' : IDL.Func([IDL.Text], [IDL.Opt(PitchCount)], ['query']),
  'getSafetyContacts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SafetyContact)],
      ['query'],
    ),
  'getSortedActivityFeed' : IDL.Func(
      [],
      [IDL.Vec(ActivityFeedEntry)],
      ['query'],
    ),
  'getWeatherData' : IDL.Func([], [WeatherData], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logPitchCount' : IDL.Func([PitchCount], [], []),
  'resolveIncident' : IDL.Func([IDL.Text], [], []),
  'startGame' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'submitSafetyChecklist' : IDL.Func([SafetyChecklist], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCredentialStatus' : IDL.Func(
      [IDL.Principal, CredentialStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SafetyContact = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'team' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const WeatherData = IDL.Record({
    'temperature' : IDL.Float64,
    'wbgt' : IDL.Float64,
    'heatCode' : IDL.Variant({
      'red' : IDL.Null,
      'orange' : IDL.Null,
      'green' : IDL.Null,
      'yellow' : IDL.Null,
    }),
    'lightningAlert' : IDL.Bool,
    'humidity' : IDL.Float64,
    'timestamp' : Time,
  });
  const FieldStatus = IDL.Variant({
    'clear' : IDL.Null,
    'pre_check_pending' : IDL.Null,
    'incident_reported' : IDL.Null,
    'game_active' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const IncidentReport = IDL.Record({
    'id' : IDL.Text,
    'resolved' : IDL.Bool,
    'description' : IDL.Text,
    'reporterId' : IDL.Principal,
    'timestamp' : Time,
    'severity' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'critical' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'photoBlobId' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
    'incidentType' : IDL.Variant({
      'near_miss' : IDL.Null,
      'injury' : IDL.Null,
      'hazard' : IDL.Null,
    }),
  });
  const GameState = IDL.Record({
    'startTime' : IDL.Opt(Time),
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'endTime' : IDL.Opt(Time),
    'winner' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'currentInning' : IDL.Nat,
    'finalScore' : IDL.Opt(IDL.Nat),
    'fieldId' : IDL.Text,
  });
  const SafetyChecklist = IDL.Record({
    'gopherHolesChecked' : IDL.Bool,
    'weatherAssessed' : IDL.Bool,
    'dugoutClear' : IDL.Bool,
    'completed' : IDL.Bool,
    'gameId' : IDL.Text,
    'fenceCappingIntact' : IDL.Bool,
    'aedLocated' : IDL.Bool,
    'basesSecured' : IDL.Bool,
    'coachId' : IDL.Principal,
    'timestamp' : Time,
    'firstAidKitPresent' : IDL.Bool,
    'pitchingMoundSafe' : IDL.Bool,
    'fieldId' : IDL.Text,
  });
  const PitchCount = IDL.Record({
    'teamName' : IDL.Text,
    'pitchCount' : IDL.Nat,
    'gameId' : IDL.Text,
    'timestamp' : Time,
    'playerName' : IDL.Text,
  });
  const CredentialStatus = IDL.Record({
    'badgeStatus' : IDL.Variant({ 'red' : IDL.Null, 'green' : IDL.Null }),
    'lastUpdated' : Time,
    'diamondLeaderComplete' : IDL.Bool,
    'backgroundCheckExpiry' : Time,
  });
  const ActivityFeedEntry = IDL.Record({
    'agent' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSafetyContact' : IDL.Func([IDL.Text, SafetyContact], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAndUpdateLightningAlert' : IDL.Func([WeatherData], [], []),
    'createField' : IDL.Func([IDL.Text, FieldStatus], [], []),
    'createIncidentReport' : IDL.Func([IncidentReport], [], []),
    'endGame' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'fetchWeatherData' : IDL.Func([], [WeatherData], []),
    'getActivityFeed' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getAllActiveGames' : IDL.Func([], [IDL.Vec(GameState)], ['query']),
    'getAllActiveIncidents' : IDL.Func(
        [],
        [IDL.Vec(IncidentReport)],
        ['query'],
      ),
    'getAllCompletedChecklistsForField' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SafetyChecklist)],
        ['query'],
      ),
    'getAllFields' : IDL.Func([], [IDL.Vec(FieldStatus)], ['query']),
    'getAllPitchCountsForPlayer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PitchCount)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChecklist' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SafetyChecklist)],
        ['query'],
      ),
    'getCredentialStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CredentialStatus)],
        ['query'],
      ),
    'getField' : IDL.Func([IDL.Text], [IDL.Opt(FieldStatus)], ['query']),
    'getGameState' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
    'getIncidentReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IncidentReport)],
        ['query'],
      ),
    'getPitchCount' : IDL.Func([IDL.Text], [IDL.Opt(PitchCount)], ['query']),
    'getSafetyContacts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SafetyContact)],
        ['query'],
      ),
    'getSortedActivityFeed' : IDL.Func(
        [],
        [IDL.Vec(ActivityFeedEntry)],
        ['query'],
      ),
    'getWeatherData' : IDL.Func([], [WeatherData], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logPitchCount' : IDL.Func([PitchCount], [], []),
    'resolveIncident' : IDL.Func([IDL.Text], [], []),
    'startGame' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'submitSafetyChecklist' : IDL.Func([SafetyChecklist], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCredentialStatus' : IDL.Func(
        [IDL.Principal, CredentialStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };