/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityFeedEntry {
  'agent' : Principal,
  'description' : string,
  'timestamp' : Time,
}
export interface CredentialStatus {
  'badgeStatus' : { 'red' : null } |
    { 'green' : null },
  'lastUpdated' : Time,
  'diamondLeaderComplete' : boolean,
  'backgroundCheckExpiry' : Time,
}
export type ExternalBlob = Uint8Array;
export type FieldStatus = { 'clear' : null } |
  { 'pre_check_pending' : null } |
  { 'incident_reported' : null } |
  { 'game_active' : null };
export interface GameState {
  'startTime' : [] | [Time],
  'team1' : string,
  'team2' : string,
  'endTime' : [] | [Time],
  'winner' : [] | [string],
  'isActive' : boolean,
  'currentInning' : bigint,
  'finalScore' : [] | [bigint],
  'fieldId' : string,
}
export interface IncidentReport {
  'id' : string,
  'resolved' : boolean,
  'description' : string,
  'reporterId' : Principal,
  'timestamp' : Time,
  'severity' : { 'low' : null } |
    { 'high' : null } |
    { 'critical' : null } |
    { 'medium' : null },
  'photoBlobId' : [] | [ExternalBlob],
  'location' : string,
  'incidentType' : { 'near_miss' : null } |
    { 'injury' : null } |
    { 'hazard' : null },
}
export interface PitchCount {
  'teamName' : string,
  'pitchCount' : bigint,
  'gameId' : string,
  'timestamp' : Time,
  'playerName' : string,
}
export interface SafetyChecklist {
  'gopherHolesChecked' : boolean,
  'weatherAssessed' : boolean,
  'dugoutClear' : boolean,
  'completed' : boolean,
  'gameId' : string,
  'fenceCappingIntact' : boolean,
  'aedLocated' : boolean,
  'basesSecured' : boolean,
  'coachId' : Principal,
  'timestamp' : Time,
  'firstAidKitPresent' : boolean,
  'pitchingMoundSafe' : boolean,
  'fieldId' : string,
}
export interface SafetyContact {
  'name' : string,
  'role' : string,
  'team' : string,
  'phone' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeatherData {
  'temperature' : number,
  'wbgt' : number,
  'heatCode' : { 'red' : null } |
    { 'orange' : null } |
    { 'green' : null } |
    { 'yellow' : null },
  'lightningAlert' : boolean,
  'humidity' : number,
  'timestamp' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSafetyContact' : ActorMethod<[string, SafetyContact], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndUpdateLightningAlert' : ActorMethod<[WeatherData], undefined>,
  'createField' : ActorMethod<[string, FieldStatus], undefined>,
  'createIncidentReport' : ActorMethod<[IncidentReport], undefined>,
  'endGame' : ActorMethod<[string, bigint, string], undefined>,
  'fetchWeatherData' : ActorMethod<[], WeatherData>,
  'getActivityFeed' : ActorMethod<[], Array<[Time, Principal, string]>>,
  'getAllActiveGames' : ActorMethod<[], Array<GameState>>,
  'getAllActiveIncidents' : ActorMethod<[], Array<IncidentReport>>,
  'getAllCompletedChecklistsForField' : ActorMethod<
    [string],
    Array<SafetyChecklist>
  >,
  'getAllFields' : ActorMethod<[], Array<FieldStatus>>,
  'getAllPitchCountsForPlayer' : ActorMethod<[string], Array<PitchCount>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChecklist' : ActorMethod<[string], [] | [SafetyChecklist]>,
  'getCredentialStatus' : ActorMethod<[Principal], [] | [CredentialStatus]>,
  'getField' : ActorMethod<[string], [] | [FieldStatus]>,
  'getGameState' : ActorMethod<[string], [] | [GameState]>,
  'getIncidentReport' : ActorMethod<[string], [] | [IncidentReport]>,
  'getPitchCount' : ActorMethod<[string], [] | [PitchCount]>,
  'getSafetyContacts' : ActorMethod<[string], Array<SafetyContact>>,
  'getSortedActivityFeed' : ActorMethod<[], Array<ActivityFeedEntry>>,
  'getWeatherData' : ActorMethod<[], WeatherData>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logPitchCount' : ActorMethod<[PitchCount], undefined>,
  'resolveIncident' : ActorMethod<[string], undefined>,
  'startGame' : ActorMethod<[string, string, string], string>,
  'submitSafetyChecklist' : ActorMethod<[SafetyChecklist], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCredentialStatus' : ActorMethod<
    [Principal, CredentialStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];