/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface CredentialStatus {
    badgeStatus: Variant_red_green;
    lastUpdated: Time;
    diamondLeaderComplete: boolean;
    backgroundCheckExpiry: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface WeatherData {
    temperature: number;
    wbgt: number;
    heatCode: Variant_red_orange_green_yellow;
    lightningAlert: boolean;
    humidity: number;
    timestamp: Time;
}
export interface PitchCount {
    teamName: string;
    pitchCount: bigint;
    gameId: string;
    timestamp: Time;
    playerName: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface GameState {
    startTime?: Time;
    team1: string;
    team2: string;
    endTime?: Time;
    winner?: string;
    isActive: boolean;
    currentInning: bigint;
    finalScore?: bigint;
    fieldId: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface IncidentReport {
    id: string;
    resolved: boolean;
    description: string;
    reporterId: Principal;
    timestamp: Time;
    severity: Variant_low_high_critical_medium;
    photoBlobId?: ExternalBlob;
    location: string;
    incidentType: Variant_near_miss_injury_hazard;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ActivityFeedEntry {
    agent: Principal;
    description: string;
    timestamp: Time;
}
export interface SafetyChecklist {
    gopherHolesChecked: boolean;
    weatherAssessed: boolean;
    dugoutClear: boolean;
    completed: boolean;
    gameId: string;
    fenceCappingIntact: boolean;
    aedLocated: boolean;
    basesSecured: boolean;
    coachId: Principal;
    timestamp: Time;
    firstAidKitPresent: boolean;
    pitchingMoundSafe: boolean;
    fieldId: string;
}
export interface SafetyContact {
    name: string;
    role: string;
    team: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FieldStatus {
    clear = "clear",
    pre_check_pending = "pre_check_pending",
    incident_reported = "incident_reported",
    game_active = "game_active"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_low_high_critical_medium {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum Variant_near_miss_injury_hazard {
    near_miss = "near_miss",
    injury = "injury",
    hazard = "hazard"
}
export enum Variant_red_green {
    red = "red",
    green = "green"
}
export enum Variant_red_orange_green_yellow {
    red = "red",
    orange = "orange",
    green = "green",
    yellow = "yellow"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSafetyContact(team: string, contact: SafetyContact): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkAndUpdateLightningAlert(currentWeather: WeatherData): Promise<void>;
    createField(id: string, status: FieldStatus): Promise<void>;
    createIncidentReport(report: IncidentReport): Promise<void>;
    endGame(gameId: string, finalScore: bigint, winner: string): Promise<void>;
    fetchWeatherData(): Promise<WeatherData>;
    getActivityFeed(): Promise<Array<[Time, Principal, string]>>;
    getAllActiveGames(): Promise<Array<GameState>>;
    getAllActiveIncidents(): Promise<Array<IncidentReport>>;
    getAllCompletedChecklistsForField(fieldId: string): Promise<Array<SafetyChecklist>>;
    getAllFields(): Promise<Array<FieldStatus>>;
    getAllPitchCountsForPlayer(playerName: string): Promise<Array<PitchCount>>;
    getCallerUserRole(): Promise<UserRole>;
    getChecklist(fieldId: string): Promise<SafetyChecklist | null>;
    getCredentialStatus(teamId: Principal): Promise<CredentialStatus | null>;
    getField(id: string): Promise<FieldStatus | null>;
    getGameState(gameId: string): Promise<GameState | null>;
    getIncidentReport(incidentId: string): Promise<IncidentReport | null>;
    getPitchCount(gameId: string): Promise<PitchCount | null>;
    getSafetyContacts(team: string): Promise<Array<SafetyContact>>;
    getSortedActivityFeed(): Promise<Array<ActivityFeedEntry>>;
    getWeatherData(): Promise<WeatherData>;
    isCallerAdmin(): Promise<boolean>;
    logPitchCount(pitchCount: PitchCount): Promise<void>;
    resolveIncident(incidentId: string): Promise<void>;
    startGame(fieldId: string, team1: string, team2: string): Promise<string>;
    submitSafetyChecklist(checklist: SafetyChecklist): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCredentialStatus(teamId: Principal, status: CredentialStatus): Promise<void>;
}
import type { CredentialStatus as _CredentialStatus, ExternalBlob as _ExternalBlob, FieldStatus as _FieldStatus, GameState as _GameState, IncidentReport as _IncidentReport, PitchCount as _PitchCount, SafetyChecklist as _SafetyChecklist, Time as _Time, UserRole as _UserRole, WeatherData as _WeatherData, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSafetyContact(arg0: string, arg1: SafetyContact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSafetyContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSafetyContact(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkAndUpdateLightningAlert(arg0: WeatherData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndUpdateLightningAlert(to_candid_WeatherData_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndUpdateLightningAlert(to_candid_WeatherData_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createField(arg0: string, arg1: FieldStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createField(arg0, to_candid_FieldStatus_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createField(arg0, to_candid_FieldStatus_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createIncidentReport(arg0: IncidentReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncidentReport(await to_candid_IncidentReport_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncidentReport(await to_candid_IncidentReport_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async endGame(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endGame(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endGame(arg0, arg1, arg2);
            return result;
        }
    }
    async fetchWeatherData(): Promise<WeatherData> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchWeatherData();
                return from_candid_WeatherData_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchWeatherData();
            return from_candid_WeatherData_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityFeed(): Promise<Array<[Time, Principal, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityFeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityFeed();
            return result;
        }
    }
    async getAllActiveGames(): Promise<Array<GameState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveGames();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveGames();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveIncidents(): Promise<Array<IncidentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveIncidents();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveIncidents();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCompletedChecklistsForField(arg0: string): Promise<Array<SafetyChecklist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCompletedChecklistsForField(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCompletedChecklistsForField(arg0);
            return result;
        }
    }
    async getAllFields(): Promise<Array<FieldStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFields();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFields();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPitchCountsForPlayer(arg0: string): Promise<Array<PitchCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPitchCountsForPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPitchCountsForPlayer(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChecklist(arg0: string): Promise<SafetyChecklist | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChecklist(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChecklist(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCredentialStatus(arg0: Principal): Promise<CredentialStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCredentialStatus(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCredentialStatus(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getField(arg0: string): Promise<FieldStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getField(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getField(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameState(arg0: string): Promise<GameState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncidentReport(arg0: string): Promise<IncidentReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentReport(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentReport(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPitchCount(arg0: string): Promise<PitchCount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPitchCount(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPitchCount(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSafetyContacts(arg0: string): Promise<Array<SafetyContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafetyContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafetyContacts(arg0);
            return result;
        }
    }
    async getSortedActivityFeed(): Promise<Array<ActivityFeedEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedActivityFeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedActivityFeed();
            return result;
        }
    }
    async getWeatherData(): Promise<WeatherData> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeatherData();
                return from_candid_WeatherData_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeatherData();
            return from_candid_WeatherData_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logPitchCount(arg0: PitchCount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logPitchCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logPitchCount(arg0);
            return result;
        }
    }
    async resolveIncident(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveIncident(arg0);
            return result;
        }
    }
    async startGame(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.startGame(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startGame(arg0, arg1, arg2);
            return result;
        }
    }
    async submitSafetyChecklist(arg0: SafetyChecklist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSafetyChecklist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSafetyChecklist(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCredentialStatus(arg0: Principal, arg1: CredentialStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCredentialStatus(arg0, to_candid_CredentialStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCredentialStatus(arg0, to_candid_CredentialStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CredentialStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CredentialStatus): CredentialStatus {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FieldStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldStatus): FieldStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_GameState_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_IncidentReport_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentReport): Promise<IncidentReport> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherData_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherData): WeatherData {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SafetyChecklist]): SafetyChecklist | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CredentialStatus]): CredentialStatus | null {
    return value.length === 0 ? null : from_candid_CredentialStatus_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FieldStatus]): FieldStatus | null {
    return value.length === 0 ? null : from_candid_FieldStatus_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameState]): GameState | null {
    return value.length === 0 ? null : from_candid_GameState_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IncidentReport]): Promise<IncidentReport | null> {
    return value.length === 0 ? null : await from_candid_IncidentReport_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PitchCount]): PitchCount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    temperature: number;
    wbgt: number;
    heatCode: {
        red: null;
    } | {
        orange: null;
    } | {
        green: null;
    } | {
        yellow: null;
    };
    lightningAlert: boolean;
    humidity: number;
    timestamp: _Time;
}): {
    temperature: number;
    wbgt: number;
    heatCode: Variant_red_orange_green_yellow;
    lightningAlert: boolean;
    humidity: number;
    timestamp: Time;
} {
    return {
        temperature: value.temperature,
        wbgt: value.wbgt,
        heatCode: from_candid_variant_n22(_uploadFile, _downloadFile, value.heatCode),
        lightningAlert: value.lightningAlert,
        humidity: value.humidity,
        timestamp: value.timestamp
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: [] | [_Time];
    team1: string;
    team2: string;
    endTime: [] | [_Time];
    winner: [] | [string];
    isActive: boolean;
    currentInning: bigint;
    finalScore: [] | [bigint];
    fieldId: string;
}): {
    startTime?: Time;
    team1: string;
    team2: string;
    endTime?: Time;
    winner?: string;
    isActive: boolean;
    currentInning: bigint;
    finalScore?: bigint;
    fieldId: string;
} {
    return {
        startTime: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.startTime)),
        team1: value.team1,
        team2: value.team2,
        endTime: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.endTime)),
        winner: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.winner)),
        isActive: value.isActive,
        currentInning: value.currentInning,
        finalScore: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.finalScore)),
        fieldId: value.fieldId
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    resolved: boolean;
    description: string;
    reporterId: Principal;
    timestamp: _Time;
    severity: {
        low: null;
    } | {
        high: null;
    } | {
        critical: null;
    } | {
        medium: null;
    };
    photoBlobId: [] | [_ExternalBlob];
    location: string;
    incidentType: {
        near_miss: null;
    } | {
        injury: null;
    } | {
        hazard: null;
    };
}): Promise<{
    id: string;
    resolved: boolean;
    description: string;
    reporterId: Principal;
    timestamp: Time;
    severity: Variant_low_high_critical_medium;
    photoBlobId?: ExternalBlob;
    location: string;
    incidentType: Variant_near_miss_injury_hazard;
}> {
    return {
        id: value.id,
        resolved: value.resolved,
        description: value.description,
        reporterId: value.reporterId,
        timestamp: value.timestamp,
        severity: from_candid_variant_n31(_uploadFile, _downloadFile, value.severity),
        photoBlobId: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.photoBlobId)),
        location: value.location,
        incidentType: from_candid_variant_n34(_uploadFile, _downloadFile, value.incidentType)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    badgeStatus: {
        red: null;
    } | {
        green: null;
    };
    lastUpdated: _Time;
    diamondLeaderComplete: boolean;
    backgroundCheckExpiry: _Time;
}): {
    badgeStatus: Variant_red_green;
    lastUpdated: Time;
    diamondLeaderComplete: boolean;
    backgroundCheckExpiry: Time;
} {
    return {
        badgeStatus: from_candid_variant_n44(_uploadFile, _downloadFile, value.badgeStatus),
        lastUpdated: value.lastUpdated,
        diamondLeaderComplete: value.diamondLeaderComplete,
        backgroundCheckExpiry: value.backgroundCheckExpiry
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    orange: null;
} | {
    green: null;
} | {
    yellow: null;
}): Variant_red_orange_green_yellow {
    return "red" in value ? Variant_red_orange_green_yellow.red : "orange" in value ? Variant_red_orange_green_yellow.orange : "green" in value ? Variant_red_orange_green_yellow.green : "yellow" in value ? Variant_red_orange_green_yellow.yellow : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Variant_low_high_critical_medium {
    return "low" in value ? Variant_low_high_critical_medium.low : "high" in value ? Variant_low_high_critical_medium.high : "critical" in value ? Variant_low_high_critical_medium.critical : "medium" in value ? Variant_low_high_critical_medium.medium : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    near_miss: null;
} | {
    injury: null;
} | {
    hazard: null;
}): Variant_near_miss_injury_hazard {
    return "near_miss" in value ? Variant_near_miss_injury_hazard.near_miss : "injury" in value ? Variant_near_miss_injury_hazard.injury : "hazard" in value ? Variant_near_miss_injury_hazard.hazard : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clear: null;
} | {
    pre_check_pending: null;
} | {
    incident_reported: null;
} | {
    game_active: null;
}): FieldStatus {
    return "clear" in value ? FieldStatus.clear : "pre_check_pending" in value ? FieldStatus.pre_check_pending : "incident_reported" in value ? FieldStatus.incident_reported : "game_active" in value ? FieldStatus.game_active : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
}): Variant_red_green {
    return "red" in value ? Variant_red_green.red : "green" in value ? Variant_red_green.green : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameState>): Array<GameState> {
    return value.map((x)=>from_candid_GameState_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncidentReport>): Promise<Array<IncidentReport>> {
    return await Promise.all(value.map(async (x)=>await from_candid_IncidentReport_n29(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FieldStatus>): Array<FieldStatus> {
    return value.map((x)=>from_candid_FieldStatus_n36(_uploadFile, _downloadFile, x));
}
function to_candid_CredentialStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CredentialStatus): _CredentialStatus {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FieldStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldStatus): _FieldStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_IncidentReport_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentReport): Promise<_IncidentReport> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_WeatherData_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeatherData): _WeatherData {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    temperature: number;
    wbgt: number;
    heatCode: Variant_red_orange_green_yellow;
    lightningAlert: boolean;
    humidity: number;
    timestamp: Time;
}): {
    temperature: number;
    wbgt: number;
    heatCode: {
        red: null;
    } | {
        orange: null;
    } | {
        green: null;
    } | {
        yellow: null;
    };
    lightningAlert: boolean;
    humidity: number;
    timestamp: _Time;
} {
    return {
        temperature: value.temperature,
        wbgt: value.wbgt,
        heatCode: to_candid_variant_n12(_uploadFile, _downloadFile, value.heatCode),
        lightningAlert: value.lightningAlert,
        humidity: value.humidity,
        timestamp: value.timestamp
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    resolved: boolean;
    description: string;
    reporterId: Principal;
    timestamp: Time;
    severity: Variant_low_high_critical_medium;
    photoBlobId?: ExternalBlob;
    location: string;
    incidentType: Variant_near_miss_injury_hazard;
}): Promise<{
    id: string;
    resolved: boolean;
    description: string;
    reporterId: Principal;
    timestamp: _Time;
    severity: {
        low: null;
    } | {
        high: null;
    } | {
        critical: null;
    } | {
        medium: null;
    };
    photoBlobId: [] | [_ExternalBlob];
    location: string;
    incidentType: {
        near_miss: null;
    } | {
        injury: null;
    } | {
        hazard: null;
    };
}> {
    return {
        id: value.id,
        resolved: value.resolved,
        description: value.description,
        reporterId: value.reporterId,
        timestamp: value.timestamp,
        severity: to_candid_variant_n17(_uploadFile, _downloadFile, value.severity),
        photoBlobId: value.photoBlobId ? candid_some(await to_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.photoBlobId)) : candid_none(),
        location: value.location,
        incidentType: to_candid_variant_n19(_uploadFile, _downloadFile, value.incidentType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    badgeStatus: Variant_red_green;
    lastUpdated: Time;
    diamondLeaderComplete: boolean;
    backgroundCheckExpiry: Time;
}): {
    badgeStatus: {
        red: null;
    } | {
        green: null;
    };
    lastUpdated: _Time;
    diamondLeaderComplete: boolean;
    backgroundCheckExpiry: _Time;
} {
    return {
        badgeStatus: to_candid_variant_n51(_uploadFile, _downloadFile, value.badgeStatus),
        lastUpdated: value.lastUpdated,
        diamondLeaderComplete: value.diamondLeaderComplete,
        backgroundCheckExpiry: value.backgroundCheckExpiry
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_red_orange_green_yellow): {
    red: null;
} | {
    orange: null;
} | {
    green: null;
} | {
    yellow: null;
} {
    return value == Variant_red_orange_green_yellow.red ? {
        red: null
    } : value == Variant_red_orange_green_yellow.orange ? {
        orange: null
    } : value == Variant_red_orange_green_yellow.green ? {
        green: null
    } : value == Variant_red_orange_green_yellow.yellow ? {
        yellow: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldStatus): {
    clear: null;
} | {
    pre_check_pending: null;
} | {
    incident_reported: null;
} | {
    game_active: null;
} {
    return value == FieldStatus.clear ? {
        clear: null
    } : value == FieldStatus.pre_check_pending ? {
        pre_check_pending: null
    } : value == FieldStatus.incident_reported ? {
        incident_reported: null
    } : value == FieldStatus.game_active ? {
        game_active: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_critical_medium): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_critical_medium.low ? {
        low: null
    } : value == Variant_low_high_critical_medium.high ? {
        high: null
    } : value == Variant_low_high_critical_medium.critical ? {
        critical: null
    } : value == Variant_low_high_critical_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_near_miss_injury_hazard): {
    near_miss: null;
} | {
    injury: null;
} | {
    hazard: null;
} {
    return value == Variant_near_miss_injury_hazard.near_miss ? {
        near_miss: null
    } : value == Variant_near_miss_injury_hazard.injury ? {
        injury: null
    } : value == Variant_near_miss_injury_hazard.hazard ? {
        hazard: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_red_green): {
    red: null;
} | {
    green: null;
} {
    return value == Variant_red_green.red ? {
        red: null
    } : value == Variant_red_green.green ? {
        green: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
